import { useState } from "react";
import { coco_applet_uri } from "utils/constants";
import dynamic from "next/dynamic";
const Modal = dynamic(() => import("components/layout/Modal"));
const TextAndAppletSlide = dynamic(() =>
   import("components/slides/TextAndAppletSlide")
);
const Paragraph = dynamic(() =>
   import("components/text").then((mod) => mod.Paragraph)
);
const ModalTriggerText = dynamic(() =>
   import("components/text").then((mod) => mod.ModalTriggerText)
);
const ModalImg = dynamic(() =>
   import("components/StyledElements").then((mod) => mod.ModalImg)
);
const Flex = dynamic(() =>
   import("components/StyledElements").then((mod) => mod.Flex)
);

const cone_unit = "assets/concept-volume-of-cone/slide2/1.svg";
const Slide2 = ({ downIcon, currentPageIdx }) => {
   const [isModalOpen, setIsModalOpen] = useState(false);
   const modalContent = (
      <Flex direction="column">
         <Paragraph color="white" marginBottom="1vh" fontSize="1.5rem">
            A right-angled triangle is a triangle in which one of its interior
            angles equal to 90 degrees.
         </Paragraph>
         <ModalImg
            src={cone_unit}
            alignSelf="center"
            width="400px"
            marginBottom="50px"
            alt="Diagram of a right angle triangle"
         />
      </Flex>
   );
   const onClick = () => {
      setIsModalOpen(!isModalOpen);
   };
   const onDismiss = () => {
      setIsModalOpen(false);
   };
   return (
      <TextAndAppletSlide
         title="Total Surface Area of Cube"
         appletSrc={`${coco_applet_uri}surface-area-of-cone-formation-v3/index.html`}
         downIcon={downIcon}
         currentPageIdx={currentPageIdx}
      >
         <Modal
            isOpen={isModalOpen}
            title="Right-angled triangle"
            content={modalContent}
            onDismiss={onDismiss}
         />
         <Paragraph>
            A right circular cone is generated by rotating a{" "}
            <ModalTriggerText id={2} onClick={onClick}>
               right-angled triangle
            </ModalTriggerText>{" "}
            about one of its sides containing the right angle.
         </Paragraph>
      </TextAndAppletSlide>
   );
};

export default Slide2;
