import { useState } from "react";
import { lineHeightProp } from "utils/fontStyles";
import dynamic from "next/dynamic";
import { ggb_applet_uri } from "utils/constants";
const Modal = dynamic(() => import("components/layout/Modal"));
const TextAndAppletSlide = dynamic(() =>
  import("components/slides/TextAndAppletSlide")
);
const Paragraph = dynamic(() =>
  import("components/text").then((mod) => mod.Paragraph)
);
const ModalTriggerText = dynamic(() =>
  import("components/text").then((mod) => mod.ModalTriggerText)
);
const ModalImg = dynamic(() =>
  import("components/StyledElements").then((mod) => mod.ModalImg)
);
const Flex = dynamic(() =>
  import("components/StyledElements").then((mod) => mod.Flex)
);

const cube_unit = "assets/surface-area-of-cone/slide3/1.svg";
const Slide3 = ({ downIcon }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const modalContent = (
    <Flex direction="column">
      <Paragraph color="white" marginBottom="1vh" fontSize="1.5rem">
        A right triangle is a triangle in which one of its interior angles is
        equal to 90 degrees.
      </Paragraph>
      <ModalImg
        src={cube_unit}
        alignSelf="center"
        width="400px"
        marginBottom="50px"
        alt="Diagram of a right angle triangle"
      />
    </Flex>
  );
  const onClick = () => {
    setIsModalOpen(!isModalOpen);
  };
  const onDismiss = () => {
    setIsModalOpen(false);
  };
  return (
    <TextAndAppletSlide
      downIcon={downIcon}
      title="Formation of a Cone"
      appletSrc={`${ggb_applet_uri}surface-area-of-cone-formation-v2/index.html`}
    >
      <Modal
        isOpen={isModalOpen}
        title="Right Triangle"
        content={modalContent}
        onDismiss={onDismiss}
      />
      <Paragraph lineHeight={lineHeightProp}>
        A right circular cone is generated by rotating a{" "}
        <ModalTriggerText id={2} onClick={onClick}>
          right triangle
        </ModalTriggerText>{" "}
        about one of its sides containing the right angle.
      </Paragraph>
    </TextAndAppletSlide>
  );
};

export default Slide3;
